version: "3" # 또는 원하는 버전

services:
  server:
    restart: always
    image: movie_server:server
    container_name: django_server
    volumes:
      - .:/app
    build: 
      context: .
      dockerfile: django.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db  

  db:
    image: postgres:15.4-alpine
    container_name: dev-db
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  pgadmin:
    container_name: Pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports: 
      - "5050:8080"

  nginx:
    container_name: nginx
    image: nginx:latest
    ports: 
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/nginx.conf:ro
      - ./server/staticfiles:/staticfiles
    depends_on:
      - server
      - daphne
  
  redis:
    image: redis:6.2.13-bookworm
    container_name: redis
    ports:
      - "6379:6379"

  daphne:
    restart: always
    image: movie_server:daphne
    container_name: daphne
    ports:
      - "6000:6000"
    build: 
      context: .
      dockerfile: daphne.Dockerfile
    volumes:
      - .:/app
    depends_on:
      - server

      
