services:
  dev-django:
    restart: always
    image: dev-django
    container_name: dev-django
    env_file:
      - env/dev.env
    volumes:
      - .:/app
    build: 
      context: .
      dockerfile: dockerfiles/django.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - dev-db

  dev-db:
    restart: always
    image: postgres:15.4-alpine
    container_name: dev-db
    env_file:
      - env/dev.env
    volumes:
      - ./data/dev/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  dev-pgadmin4:
    restart: always
    image: dpage/pgadmin4:latest
    container_name: dev-pgadmin4
    env_file:
      - env/dev.env
    volumes:
      - ./data/dev/pgadmin:/var/lib/pgadmin
    ports: 
      - "5050:80"
    depends_on:
      - dev-db
  
  dev-redis:
    image: redis:6.2.13-bookworm
    container_name: dev-redis
    ports:
      - "6379:6379"

# 추후 추가해야 함
  # dev-celery:
  #   restart: always
  #   build: 
  #     context: .
  #   command: celery -A core worker -l INFO
  #   volumes:
  #       - .:/app
  #   container_name: celery
  #   depends_on:
  #     - db
  #     - redis
  #     - django_gunicorn
